### PR TITLE
Update method of getting Product Code from installer

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Updated method of getting Product Code from the installer which works on PS5 and PS5+.

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Is that working with PS5 and PS7? That's a way smarter line

**Comment by vedantmgoyal2009** [comment]
> Is that working with PS5 and PS7? That's a way smarter line

Yes tested on 5.1.22000.65 and 7.1.3

**Comment by vedantmgoyal2009** [comment]
I may have asked this before from Trenly... but can we add #21940 in YamlCreate.ps1 v2.0.0 as it is already a major update.

**Comment by OfficialEsco** [comment]
Ofc, I feel like the PR will be stuck for a month or two minimum so implement whatever and test the code for silly PS5 compatability

**Review by OfficialEsco — APPROVED** [review]

**Comment by quhxl** [comment]
Is it not wanted that the ProductCode is simply transferred when pressing Enter? Is the error rate too high? Has simply nobody thought about it?

**Comment by OfficialEsco** [comment]
Since vedantmgoyal2009 added the Pattern there should be no miss matches, however in cases of Mozilla Firefox we don't actually want the ProductCode since its not actually the ProductCode of the software...
We can easily do it yes, maybe we could do "Do you want to use this ProductCode?"

**Comment by quhxl** [comment]
I don't know if we should do that because I think we should try to include as few prompts as possible and only as many as necessary.

**Pull request merged**
