### PR TITLE
Auto Mode

### PR DESCRIPTION
**Pull request by Trenly**
@OfficialEsco This should help for packages with Static URL's
`.\YamlCreate.ps1 -AutoUpdate`
`.\YamlCreate.ps1 Google.Chrome 94.0.4606.6` -> microsoft#28530

-----
Enable the setting: 
```powershell
"`nEnableDeveloperOptions: true" |
Out-File -Encoding ASCII -append  $(Join-Path $env:LOCALAPPDATA -ChildPath 'YamlCreate\Settings.yaml')
```

-----

### CODE REVIEW

**Comment by OfficialEsco** [comment]
A bit hard to test as of now, but i did force a issue:
If the PackageVersion is the same the script crashes 👀

**Comment by Trenly** [comment]
> A bit hard to test as of now, but i did force a issue:
> If the PackageVersion is the same the script crashes 👀

Should be fixed now; Forgot that it could be used to update singletons to multimanifests

**Comment by OfficialEsco** [comment]
That is actually not what i was thinking about, but it does solve all those issues 😁

Since i doubt i can test this, there is no ProductCode prompt, so how is the ProductCode logic?
I think this is mergable if the answer is the way i think it works 👌

**Comment by Trenly** [comment]
> That is actually not what i was thinking about, but it does solve all those issues 😁
> 
> Since i doubt i can test this, there is no ProductCode prompt, so how is the ProductCode logic?
> I think this is mergable if the answer is the way i think it works 👌

If the installer 

> That is actually not what i was thinking about, but it does solve all those issues 😁
> 
> Since i doubt i can test this, there is no ProductCode prompt, so how is the ProductCode logic?
> I think this is mergable if the answer is the way i think it works 👌

It attempts to find the product code for all installers. If it finds one in the AppLocker info, it will add/update the product code to be the one found. If it cannot find one, it removes any old values and leaves it undefined as it is an optional field

**Review by OfficialEsco — APPROVED** [review]
I'm fine with that, pretty sure Wingetcreate and wingetbot dosn't even remove the old ProductCode if it dosn't find one which causes issues..

There is however one ProductCode issue overall, we add the ProductCode to some exe installers that don't have Publisher/PackageName, these are not inside bracket `{ }` and they are static.

Currently we have to retype them or in this add it after, would you be able to Capture this and add it to the ProductCode variable?

Approving since this needs to change in more places

**Comment by Trenly** [comment]
> There is however one ProductCode issue overall, we add the ProductCode to some exe installers that don't have Publisher/PackageName, these are not inside bracket `{ }` and they are static.
> 
> Currently we have to retype them or in this add it after, would you be able to Capture this and add it to the ProductCode variable?
> 

I think it would be possible to add the logic for if the installer file ends in `.exe` and has a product code defined, don't remove the product code; Unless you think it needs to be more complex than that?

**Comment by OfficialEsco** [comment]
Ooooo yes that would probably be a better detection method

**Comment by Trenly** [comment]
> Ooooo yes that would probably be a better detection method

Easy to add too; See latest commit

**Comment by OfficialEsco** [comment]
That feature also needs to be added to option 2 btw

**Comment by Trenly** [comment]
> That feature also needs to be added to option 2 btw

Updated there too; Had to use installer type in that case because of the option to not download the file, but it should be functionally equivalent

**Comment by OfficialEsco** [comment]
Aight it does work as expected
However its a lill bit too unfriendly when using simple update

This part needs a rework
```
[Optional] Enter the application product code. Looks like {CF8E6E00-9C03-4440-81C0-21FACB921A6B}
ProductCode found from installer:
Can be found with get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize
ProductCode:
```

**Review by OfficialEsco — APPROVED** [review]

**Comment by Trenly** [comment]
> Aight it does work as expected
> However its a lill bit too unfriendly when using simple update
> 
> This part needs a rework
> 
> ```
> [Optional] Enter the application product code. Looks like {CF8E6E00-9C03-4440-81C0-21FACB921A6B}
> ProductCode found from installer:
> Can be found with get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize
> ProductCode:
> ```
> 
> Prolly better to merge this and do another PR?

Yeah; Probably best to handle it separately; Ideally it should detect the product code automatically and handle the same as autoupdate?

**Comment by OfficialEsco** [comment]
> Yeah; Probably best to handle it separately; Ideally it should detect the product code automatically and handle the same as autoupdate?

Yeah i guess we can add the ProductCode automatically as that is requested

I still think we should have this prompt sort of

If ProductCode found
```
[Optional] Enter the application product code.
ProductCode found from installer:
Note: If this is incorrect input the correct ProductCode, else press Enter
ProductCode:
```

If not found (MSI and EXE?)
```
[Optional] Enter the application product code.
Note: Can be in the registry at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\`
ProductCode:
```

Optional for MSI if not found
```
[Optional] Enter the application product code. Looks like {CF8E6E00-9C03-4440-81C0-21FACB921A6B}
Can be found with get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize
ProductCode:
```

**Pull request merged**
