### PR TITLE
Yaml parsing rebase

### PR DESCRIPTION
**Pull request by Trenly**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by Trenly** [comment]
@OfficialEsco  I'd like to rebase the [YamlParsing branch](https://github.com/Trenly/winget-pkgs/tree/YamlParsing) on the [Microsoft master branch](https://github.com/microsoft/winget-pkgs/tree/master).

The YamlParsing file hasn't changed at all -
```raw
PS D:\Git\winget-pkgs> git diff YamlParsing YamlParsingRebase -- .\Tools\YamlCreate.ps1

PS D:\Git\winget-pkgs>
```

This would just be pulling in the last 1700 or so commits. I'd appreciate if you could review and make sure I didn't mess up the rebase before I merge all of the commits in

**Comment by OfficialEsco** [comment]
noooot sure what you want me to look at that you cannot see your self 😁

**Comment by Trenly** [comment]
> noooot sure what you want me to look at that you cannot see your self 😁
> 

Sometimes I just like a second set of eyes just to be sure;

> Edit:
> Also you should open this repo for issues so we can request/discuss ideas
> For example we need to remove the en-US requirement from the Installer, which i tried to fix but i believe null is not a valid variable so it failed
>
It is a public repo; It's just that you and I are the only ones with write access
image

**Comment by OfficialEsco** [comment]
image

You have to enable Issue in the settings 😬
image

**Comment by Trenly** [comment]
> Kinda hard when 4k+ different changes 😁git rebase usually don't cause issues other than a random merge commit that comes at the end for some reason
> 
> image
> 
> You have to enable Issue in the settings 😬
> image

Ahh, I missed those checkboxes. Should be enabled now

**Pull request merged**
