### PR TITLE
Check for productcode even if extension doesn't match

### LINKED ISSUE #150: Check for ProductCode if url does not end with .msi
Moving the issue here so we don't clutter the other thread 😁

> > However, it is checked to see if the extension is MSI to determine whether or not to check for the ProductCode
> 
> Hmm, shouldn't this also be based on the InstallerType then? if Extension or InstallerType eq msi or eq wix check for ProductCode?
>
>It is, but the automatic installer type detection is what this kind of determines. If the filetype is automatically determined to be a `.msi` then it will automatically select either msi or wix without asking for input, same with msix or appx. 
>```
>Try to determine file extension from URL
>If file extension is msi, msix, or appx, automatically select the installer type
>    Else - Ask for user input
>If installer type is ____ do _____ 
>    * msi/wix automatically get product code
>    * msix/appx automatically try to get PFN
>    * etc
>```

_Originally posted by @Trenly in https://github.com/Trenly/winget-pkgs/issues/148#issuecomment-1031535540_

```
Selection: 1

[Required] Enter the Package Identifier, in the following format <Publisher shortname.Application shortname>. For example: Microsoft.Excel
PackageIdentifier: Microsoft.RemoteDesktopClient

[Required] Enter the version. for example: 1.33.7
Version: 1.2.2688.1
Found Existing Version: 1.2.2688.0

[Required] Enter the download url to the installer.
Url: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWQvmX


Downloading URL. This will take a while...
Time taken: 0 second(s)

[Required] Enter the architecture. Options: x86, x64, arm, arm64, neutral
Architecture: x64

[Required] Enter the InstallerType. Options: msix, msi, appx, exe, zip, inno, nullsoft, wix, burn, pwa
InstallerType: wix

[Optional] Enter the silent install switch. For example: /S, -verysilent, /qn, --silent, /exenoui
Silent switch:

[Optional] Enter the silent with progress install switch. For example: /S, -silent, /qb, /exebasicui
Silent with progress switch:

[Optional] Enter any custom switches for the installer. For example: /norestart, -norestart
Custom Switch:

[Optional] Enter the installer locale. For example: en-US, en-CA
https://docs.microsoft.com/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
InstallerLocale:


[Optional] Enter the application product code. Looks like {CF8E6E00-9C03-4440-81C0-21FACB921A6B}
ProductCode found from installer:
Can be found with get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize
ProductCode:
```

So, you're saying the Automatic detection needs to detect it and the manual entry does not trigger it?
That means it will not check for a ProductCode if the url does not end with .msi even when the InstallerType is defined as msi or wix

### PR DESCRIPTION
**Pull request by Trenly**
* Closes #150
@OfficialEsco This should do what you wanted, but I will warn you that if the installer type is MSI or WIX and the file that is downloaded is not truly an MSI file then it will likely error out.  The more intelligent that we try to make things, the bigger the chance that incorrect input will cause things to go 💥

### CODE REVIEW

**Comment by OfficialEsco** [comment]
weeeell, if its not .msi @vedantmgoyal2009 got a problem

it did however fail to identify it as wix 🤔

**Comment by Trenly** [comment]
@OfficialEsco Also think I fixed this one; Some light testing allowed it to detect the ProductCode using `https://sourceforge.net/projects/scidavis/files/SciDAVis/2/2.7/scidavis.2.7-win-dist.msi/download` as the download link in quick update mode. Doesn't work in Full Update mode because the detection happens before InstallerType is specified, but will look to fix that separately since it requires a bit more refactoring.

**Comment by OfficialEsco** [comment]
Oh yeah as i said

> it did however fail to identify it as wix 🤔

Step to replicate

```
PS .\Tools\YamlCreate.ps1 -AutoUpgrade -SkipPRCheck -PackageIdentifier Microsoft.RemoteDesktopClient -PackageVersion 1.2.2688.0


Found Existing Version: 1.2.2688.0

Updating Manifest Information. This may take a while...

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Microsoft\RemoteDesktopClient\1.2.2688.0\Microsoft.RemoteDesktopClient.locale.en-US.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Microsoft\RemoteDesktopClient\1.2.2688.0\Microsoft.RemoteDesktopClient.installer.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Microsoft\RemoteDesktopClient\1.2.2688.0\Microsoft.RemoteDesktopClient.yaml
Manifest validation succeeded.


Do you want to submit your PR now?
  [Y] Yes
  [N] No

Enter Choice (default is 'Y'): n
```
or

```
PS .\Tools\YamlCreate.ps1 -mode 2 -SkipPRCheck -PackageIdentifier Microsoft.RemoteDesktopClient -PackageVersion 1.2.2688.0

Found Existing Version: 1.2.2688.0
Installer Entry #1:

        Architecture: x64
        InstallerType: msi
        Scope: user


[Required] Enter the download url to the installer.
Url: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWQvmX
Downloading Installer. . .
Installer Downloaded!
Processing installer data. . .
Installer updated!

Installer Entry #2:

        Architecture: x64
        InstallerType: msi
        Scope: machine


[Required] Enter the download url to the installer.
Url: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWQvmX
Installer Entry #3:

        Architecture: x86
        InstallerType: msi
        Scope: user


[Required] Enter the download url to the installer.
Url: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWQvmX
Installer Entry #4:

        Architecture: x86
        InstallerType: msi
        Scope: machine


[Required] Enter the download url to the installer.
Url: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWQvmX
Installer Entry #5:

        Architecture: arm64
        InstallerType: msi
        Scope: user


[Required] Enter the download url to the installer.
Url: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWQvmX
Installer Entry #6:

        Architecture: arm64
        InstallerType: msi
        Scope: machine


[Required] Enter the download url to the installer.
Url: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWQvmX

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Microsoft\RemoteDesktopClient\1.2.2688.0\Microsoft.RemoteDesktopClient.locale.en-US.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Microsoft\RemoteDesktopClient\1.2.2688.0\Microsoft.RemoteDesktopClient.installer.yaml

Yaml file created: C:\Users\Esco\GitHub\winget-pkgs\manifests\m\Microsoft\RemoteDesktopClient\1.2.2688.0\Microsoft.RemoteDesktopClient.yaml
Manifest validation succeeded.


Do you want to submit your PR now?
  [Y] Yes
  [N] No

Enter Choice (default is 'Y'): n
```

InstallerType remains msi

**Comment by OfficialEsco** [comment]
Late update but i have used this since the change and not had issues other than when i fked up + the no wix detection
But we probably need a safer method for bots

**Pull request closed without merging**
