### PR TITLE
Settings switch

### LINKED ISSUE #47: Sub-command/Switch for opening settings directly
# Description of the new feature/enhancement

Instead of users finding the Settings.yaml file manually by browsing through directories, I would like to have a sub-command/switch that would open the Settings file directly in Notepad or any preferred editor. Something like this would work:
```
YamlCreate.ps1 -settings
```

### PR DESCRIPTION
**Pull request by Trenly**
* `.\YamlCreate.ps1 -Settings` now opens the settings file
* `.\YamlCreate.ps1 -Settings` now shows a link to the documentation and command line usage for YamlCreate
* `.\YamlCreate.ps1 -PackageIdentifier <identifier>` can be used to skip the package identifier prompt
* `.\YamlCreate.ps1 -PackageVersion <version>` can be used to skip the package version prompt
* `.\YamlCreate.ps1 -PackageIdentifier <identifier> -PackageVersion <version>` can be used to skip both the package identifier and package version prompt

-----
* Resolves #47

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@Trenly Since you have added a switch for PackageIdentifier and PackageVerison, I thought that if we can directly do:
```
.\YamlCreate.ps1 abc.abc 1.0.0
```
Also, I think it would issues for new users so we can disable the functionality by default, and enable it using:
```
EnableExperimentalArgs: <true|false>
```
> This is just a suggestion. If it seems good, can we implement it as well?

**Comment by OfficialEsco** [comment]
> I thought that if we can directly do:
> 
> ```
>.\YamlCreate.ps1 abc.abc 1.0.0
>```

I'm a newbie to Param, but i believe this can be achieved with `Position=` [Specifying PowerShell Parameter Position](https://www.powershellstation.com/2017/10/04/specifying-powershell-parameter-position/)

> Also, I think it would issues for new users so we can disable the functionality by default, and enable it using:
>```
>EnableExperimentalArgs: <true|false>
>```

This could probably be a feature yes, but i'm not sure if newbies will try/use `- tab` tho?

**Comment by vedantmgoyal2009** [comment]
image
After reading this, I ran `.\YamlCreate.ps1 abc.abc 1.0.0` and it worked. I should have tested it before commenting 😐.

**Comment by Trenly** [comment]
It might be confusing and add unnecessary logic to have a setting that turns off the parameters, since command parameters are an integral part of PowerShell. Any values entered through the parameters are still validated to conform to the schema, and I think that having the documentation is sufficient to describe what they do.  We don’t have to make the script account for every possible errror and for those who are new to using the script there is still the option to use no arguments. This follows the same precedent set by most other files which can be run from the command line

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
