### PR TITLE
Differentiate between Upgrade and New Version

### PR DESCRIPTION
**Pull request by OfficialEsco**
Hmm, not sure if it should be `Add Version` or `New Version`, i kinda like `New Version` tbh

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@quhxl any reason for using `Add Version` over `New Version` as you've chosen `Add Version` for your PRs?

**Comment by quhxl** [comment]
All types I think are good as long as they create consistency."New version" is great if a version is added to an existing package. Maybe "New package" if a completely new package is added. Also, maybe "Update metadata" if the hash doesn't change, but only other parts of the manifest.

**Comment by OfficialEsco** [comment]
> All types I think are good as long as they create consistency."New version" is great if a version is added to an existing package. 

I actually forgot the reasoning behind why i went with `Add Version` too 🤦‍♂️ Its because we sometimes add older versions, but we can probably easily add greater or lower value than current version

> Maybe "New package" if a completely new package is added. 

We do have `New:` but we can probably do `New Package:` for clarity

> Also, maybe "Update metadata" if the hash doesn't change, but only other parts of the manifest.

The technology is not there yet 😬 Should be easy to add when we get `Simple Update` working tho

**Comment by vedantmgoyal2009** [comment]
My views are:

New version -> For adding older versions
Update -> For adding a new version (Add version also works here)
New -> For new pacakge
Locale -> For new locale

**Comment by OfficialEsco** [comment]
naaaaaaaah that doesn't sound right
```
New Version     = Newly Released version added (Anything newer than whats in the repo from before)
Add Version     = Just another version but lower than whats in Repo
Update          = You updated a already existing versions Metadata but its mainly for the Installer.yaml
New/New Package = Brand new Pacakge
Locale          = When you only change a locale.yaml
Metadata        = Changes to en-US Locale
```

Me and @quhxl update all the Metadata at once so we don't spam PR's which is why Update should be something else as it looks weird the way it is now

**Comment by vedantmgoyal2009** [comment]
> Me and @quhxl update all the Metadata at once so we don't spam PR's which is why Update should be something else as it looks weird the way it is now

I am not interested in that now, I make my own scripts and find mistakes/vulnerabilities in the repository and then correct them. I soon realised that updating metadata is one of the most boring things for me. While making scripts, I learn new things and it is more interesting than updating metadata.

**Comment by OfficialEsco** [comment]
> I am not interested in that now, I make my own scripts and find mistakes/vulnerabilities in the repository and then correct them. I soon realised that updating metadata is one of the most boring things for me. While making scripts, I learn new things and it is more interesting than updating metadata.

Well yes its boring when its mostly Pointless to update old manifests of old versions as long as it don't cause issues with the current packages. However its pointless when you update one thing and multiple other parts are wrong and waste the moderators time by having to suggest changes or you submit another PR and waste even more time.

This also goes for scripts, it seems like you don't actually test if the function works as expected, which then wastes even more time.

**Comment by quhxl** [comment]
I also think that when dealing with a manifest, you should try to add as much metadata as possible. Single small changes to very old manifests only consume everyone's time. If I find mismatched ARP data, then I have to deal with the manifest anyway, may as well add some links or other things.

**Comment by quhxl** [comment]
Shouldn't the "version" and "package" be lowercase?

**Comment by OfficialEsco** [comment]
Updated to lowercase now, its just the way i prefer to see it written but its not the correct way 😁

**Comment by Trenly** [comment]
> Updated to lowercase now, its just the way i prefer to see it written but its not the correct way 😁
> Should we go as far as `Update version:` ?🤔 or is that too long?

I think just leaving it as update would be fine for now, until we incorporate the simple update.

**Review by Trenly — APPROVED** [review]

**Pull request merged**
