### PR TITLE
Fixes microsoft/winget-pkgs#21219 + some more improvements

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
Fixes microsoft/winget-pkgs#21219

### CODE REVIEW

**Comment by quhxl** [comment]
I don't really like the title. It is rather a simplified possibility to change only single parameters in usually already good manifests. Updates are still possible via "New Package" and adding metadata when updating should remain the preferred way, in my opinion.

**Comment by vedantmgoyal2009** [comment]
> I don't really like the title. It is rather a simplified possibility to change only single parameters in usually already good manifests. Updates are still possible via "New Package" and adding metadata when updating should remain the preferred way, in my opinion.

I really don't get what you mean to say.

**Comment by vedantmgoyal2009** [comment]
> Fixes [microsoft#21219](https://github.com/microsoft/winget-pkgs/issues/21219)

Please DO NOT test the script as the work is in progress.

**Comment by quhxl** [comment]
The selection options have been renamed. So it seems that the new option, where only the most necessary is changed, is the preferred one for updates. I think that the formulation of the options must be in a way that it is clear that the option with the queries for all metadata is still the preferred one. The new option should only be for quick updates. Otherwise, we would have to deal with each manifest twice to add the metadata afterwards if all users use this stripped-down mode in the first place.

**Comment by vedantmgoyal2009** [comment]
@quhxl Line 250 https://github.com/Trenly/winget-pkgs/blob/0dad55e7a4e2153be667408db05be9b6785a081c/Tools/YamlCreate.ps1#L249-L254

**Comment by vedantmgoyal2009** [comment]
From https://github.com/microsoft/winget-pkgs/issues/21219#issue-946529481
> method 1
> Prompt for every different InstallerUrl so it can replace multiple installers at once
> 
> method 2
> If version number is in the InstallerUrl try to replace Version Numbers, if 404 prompt for url
> 
> another feature:
> If installerUrl dosn't change delete the previous manifest version

@OfficialEsco Can't method 2 be solved by method 1?
And, in "another feature" I think we have to submit two PR, first of deleting the old version and then adding a new version.

**Comment by OfficialEsco** [comment]
Tested this a little, and it does work as expected, but i was kinda thinking less prompts.
Also to be more clear
Method 1:
```
**Write**
InstallerLocale: en-US
Architecture: x64
InstallerType: nullsoft
Scope: user

**Request string**
Insert InstallerUrl: 
Insert ProductCode:

**Write**
InstallerLocale: en-US
Architecture: x64
InstallerType: nullsoft
Scope: machine

**Request string**
Insert InstallerUrl: 
Insert ProductCode:

**Write**
InstallerLocale: en-US
Architecture: x86
InstallerType: nullsoft
Scope: user

**Request string**
Insert InstallerUrl: 
Insert ProductCode:

**Write**
InstallerLocale: en-US
Architecture: x86
InstallerType: nullsoft
Scope: machine

**Request string**
Insert InstallerUrl: 
Insert ProductCode:
```
if missing strings 
```
**Write**
Architecture: x86
InstallerType: nullsoft

**Request string**
Insert InstallerUrl: 
Insert ProductCode:
```

Alternatively
```
**Write**
Installer: nullsoft x64 en-US user

**Prompt**
Insert InstallerUrl: 
Insert ProductCode:
```

> @OfficialEsco Can't method 2 be solved by method 1?

Method 2 could try to replace the URL, if it returns 404 it will go to Method 1

> And, in "another feature" I think we have to submit two PR, first of deleting the old version and then adding a new version.

No it does not because the URL is static
```
Read Previous Manifest
Create New Manifest
Delete old Manifest if InstallerURL is the same
Push Commit
Create PR
```
Or
```
Read Previous Manifest
Create New Manifest
Push Commit
Check if InstallerURL matches previous version
If match Delete old Manifest
Push Commit
Create PR
```

**Comment by vedantmgoyal2009** [comment]
It will take some time for me to understand how the module `powershell-yaml` works and then I will implement [these](https://github.com/Trenly/winget-pkgs/pull/23#issuecomment-909674068) features as well.

**Comment by vedantmgoyal2009** [comment]
I have been able to work with singleton manifests but dealing with multi-manifest is too difficult. @Trenly please help🙏.

**Comment by Trenly** [comment]
I can look into it, but one big area that I need to get done first is using the high level parameters for installers since thats causing a few bugs.

I think the deletion flow is also a bit more complicated than it seems. I’ll try and put together a logic diagram for it just so we can all align on it before we implement

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco @Trenly we have to work on this also(?) I think we have to change the way the script downloads the URLs?
image

**Comment by vedantmgoyal2009** [comment]
I will be opening a new PR because while checking out, I ran `git pull` by mistake. Sorry.

**Pull request closed without merging**
