### PR TITLE
Begin Handling Manifest Level Parameters

### LINKED ISSUE #30: YamlCreate does not handle manifest-level parameters
# Brief description of your issue
Some manifests define installer parameters at the manifest level instead of at the installer level. YamlCreate is unable to properly handle these

# Expected behavior
Manifest level parameters should be parsed properly

# Proposed solution
When parameters are defined at the manifest level, reading of the previous installer manifest should remove them from the manifest level and add them to every installer at the installer level. This will allow for #29 to be more robust in the event any updates are made to installers which would make these parameters unable to be defined at the manifest level after update

### PR DESCRIPTION
**Pull request by Trenly**
Resolves #30 
------

@OfficialEsco I've begun handling and condensing parameters to and from the manifest level. I haven't tested this at all yet, but I'm 80% confident the main functionality is there if you'd like to help me find the bugs.

I still want to complete the rework to update the manifests in-place as part of this too, but I don't think that needs to be complete to test.

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Whoa, i thought i could force a issue but it worked as expected O_O

However i found another part of the script that got broken in one of the last patches, when updating with option 1 it failed to read the InstallModes

**Comment by Trenly** [comment]
> Whoa, i thought i could force a issue but it worked as expected O_O
> 
> However i found another part of the script that got broken in one of the last patches, when updating with option 1 it failed to read the InstallModes

As in, forgot to read the existing value, or forgot to request them, or forgot to write it to file?

**Comment by OfficialEsco** [comment]
AFAIK option 1 fails to read the existing InstallModes value

**Comment by Trenly** [comment]
> AFAIK option 1 fails to read the existing InstallModes value

Took a while to find the issue, but I found it. Should be fixed now

**Comment by Trenly** [comment]
Upon further consideration; The refactor for updating in place isn't of high priority and will take some time; I think that resolving this bug is too important to hold for the UpdateInPlace

@OfficialEsco  If you could give this a few cycles, I'd like to make 100% sure this doesn't introduce any new bugs before merging

**Comment by vedantmgoyal2009** [comment]
It is off-topic but I would suggest adding a comment like this so that moderators would know which mode was used while creating manifests and also, it will make it easier to suggest changes if a manifest contains wrong information.
```
Created with YamlCreate.ps1 v2.0.0 using YAML parsing with <Quick Update | Full Update | etc...>
```

**Comment by vedantmgoyal2009** [comment]
I have used it in my last 20+ PRs and it works fine.

**Review by OfficialEsco — APPROVED** [review]
Works like a charm

**Pull request merged**
