### PR TITLE
Clear volatile fields 1.1.0

### PR DESCRIPTION
**Pull request by Trenly**
@OfficialEsco 

I haven't added the prompts for these values into the quick update yet, since that gets a bit more tricky. This PR should allow the fields to be updated using the full flow (Option 1), and will clear them if empty, or if Option 2 or AutoUpdate is used

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
Seems good to me, quick second approval from @jedieaston and @vedantmgoyal2009 wouldn't hurt

**Comment by Trenly** [comment]
> Seems good to me, quick second approval from @jedieaston and @vedantmgoyal2009 wouldn't hurt

I did do some testing, so I'm fairly confident. I'll wait for Easton's approval before merging though

**Review by jedieaston — APPROVED** [review]
LGTM!

**Review by vedantmgoyal2009 — APPROVED** [review]
:shipit:

**Pull request merged**
