### PR TITLE
Compare versions properly

### LINKED ISSUE #117: [New Feature]: Neutral/Better if newer version
### Description of the new feature/enhancement

Currently we sometimes see `Add version:` when its actually a `New version:`

### Proposed technical implementation details (optional)

Not sure if we're already sorting the current versions as neutral?

### PR DESCRIPTION
**Pull request by Trenly**
@OfficialEsco 
- Resolves #117

### CODE REVIEW

**Comment by Trenly** [comment]
@OfficialEsco If you want me to rebase these on the latest to make testing easier LMK

**Comment by OfficialEsco** [comment]
Naah i cherry picked every branch into 1 on my repo ^^ Just doing testing under normal usage which is why some PR's gets approved slowly as they require a bit more stable testing

**Comment by Trenly** [comment]
> Naah i cherry picked every branch into 1 on my repo ^^ Just doing testing under normal usage which is why some PR's gets approved slowly as they require a bit more stable testing
> 
Fair point; Just didn't know if it was easy for you

> Edit: not sure how much you test your code, but if you do you'll probably pick a few that is mentioned, which doesn't always cover every corner (:
> 
Depends on the case. If the issue is clear and easy to solve like the architecture bug, I do a little less testing. For more complex things, I do a little more testing. 

> Edit2: I daily drive every patch, however i'm not sure what the state of #112 is, also its probably a bit too early to use since we don't have all the areas covered (MS Side)
>
I'm thinking of waiting on #112 for a bit. I know there is a bug open for release date validation. I'm going to mark #112 as draft probably, just since it isn't critical to be merged in

**Comment by OfficialEsco** [comment]
Well, here is one issue https://github.com/microsoft/winget-pkgs/pull/36724
Also looks like i missed this one https://github.com/microsoft/winget-pkgs/pull/36633

**Comment by Trenly** [comment]
2 of those are intentional; Yes

Can you describe the issuse with each of those three packages in a bit more detail?

**Comment by OfficialEsco** [comment]
Nevermind, all of those are actually a trigger of 1 version in the repo
* Guilded: Dynamic url, AutoUpgrade
* SubSync: there was 1 version in there, Simple Update
* Sandboxie.Plus: I submitted `0.9.8d` first, dragged those files into the folder and SimpleUpgraded to `1.0.0.0.0` so i expected `New version:` instead of `New package:`

The .Count line should probably be last in the elseif's or rewritten so it dosn't trigger when there already is a version in there. (Because i regularly update Dynamic urls and it looks weird when it always says `New package:`)

**Comment by Trenly** [comment]
> Nevermind, all of those are actually a trigger of 1 version in the repo
> 
> * Guilded: Dynamic url, AutoUpgrade
> * SubSync: there was 1 version in there, Simple Update
> * Sandboxie.Plus: I submitted `0.9.8d` first, dragged those files into the folder and SimpleUpgraded to `1.0.0.0.0` so i expected `New version:` instead of `New package:`
> 
> The .Count line should probably be last in the elseif's or rewritten so it dosn't trigger when there already is a version in there. (Because i regularly update Dynamic urls and it looks weird when it always says `New package:`)

Ahh, fair point. I’ll take a look at those cases and see where the logic needs to change

**Comment by Trenly** [comment]
> * Guilded: Dynamic url, AutoUpgrade
>
I believe this is fixed

> * SubSync: there was 1 version in there, Simple Update
>
I believe this is fixed

> * Sandboxie.Plus: I submitted `0.9.8d` first, dragged those files into the folder and SimpleUpgraded to `1.0.0.0.0` so i expected `New version:` instead of `New package:`
> 
Not entirely sure what happened here. I wasn't able to replicate.  If it is still happening, maybe we can chat on Gitter to figure it out?

> The .Count line should probably be last in the elseif's or rewritten so it dosn't trigger when there already is a version in there. (Because i regularly update Dynamic urls and it looks weird when it always says `New package:`)
>
This actually was the root cause of both issues that were resolved. If there was only one version of the package, it was automatically casting the variables as strings. I explicitly cast them as arrays, which should have fixed the issue

**Review by OfficialEsco — APPROVED** [review]
I've not had too many weird packages, but as far as i can tell this is working as expected

**Pull request merged**
