### PR TITLE
Write Unused Keys as Comments

### PR DESCRIPTION
**Pull request by Trenly**
@OfficialEsco - Could I trouble you for a review?

As a side note, I decided to not have it enumerate every single one of the fields available under `Installers:`  just because it got to be a lot (especially with more than one installer). Everything else should work though

### CODE REVIEW

**Comment by Trenly** [comment]
@OfficialEsco Would you like one last review before I merge this in?

I'll be looking at how to do the adaptive manifest in a separate PR

**Comment by OfficialEsco** [comment]
I used this one until vedantmgoyal2009 made simple update PR, so it should be 👌

**Review by OfficialEsco — APPROVED** [review]

**Comment by Trenly** [comment]
> I used this one until vedantmgoyal2009 made simple update PR, so it should be 👌

Perfect

**Comment by OfficialEsco** [comment]
I accidentally found a issue

```
Select Mode

[1] New Manifest or Package Version

[2] Update Package Metadata

[3] New Locale

[q] Any key to quit

Selection: 2

[Required] Enter the Package Identifier, in the following format <Publisher shortname.Application shortname>. For example: Microsoft.Excel
PackageIdentifier: Bethesda.Launcher

[Required] Enter the version. for example: 1.33.7
Version: 1.82.0

Could not find required manifests, input a version containing required manifests or "exit" to cancel
Version:
```
image

**Comment by Trenly** [comment]
@OfficialEsco This is because 1.82.0 was only recently added into the manifests. If you look at the [YamlParsing Branch](https://github.com/Trenly/winget-pkgs/tree/YamlParsing/manifests/b/Bethesda) it only has the `1.75.0` version. The update metadata command requires exact version matching, so if you're on the YamlParsing branch, 1.82.0 doesn't exist yet since it hasn't been rebased in the past 4 hours.

One way to verify that this is the root cause is to checkout the upstream master branch, then run `git checkout YamlParsing -- .\Tools\YamlCreate.ps1`. After doing this, if you run the script, it will find 1.82.0 (You just have to be careful to manually unstage the YamlCreate script before telling it to automatically submit the PR if you do this)

**Comment by OfficialEsco** [comment]
Naaaaaaaaaaa i was just duuuuuumb, this "accidental" issue was from BEFORE i generated the 1.82.0 manifest 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

I have a local branch which i regularly rebase, but that dosn't help when i didn't create a version in the first place...

**Pull request merged**
