### PR TITLE
Add delete manifest functionality

### PR DESCRIPTION
**Pull request by Trenly**

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Just to be sure, how does this actually work?
Does it only trigger when you select option 5?

I've implemented #38 and this which did cause a conflict but i believe it was just spacing difference.

AFAIK you can't delete a manifest and submit and a new manifest?
Also i think for it to work the way i want it to work it needs to

1. Create a new Manifest
2. Delete the old Manifest
3. Commit as `New Version: Publisher.PacakgeName version 1.3.3.7`
4. Publish PR
Example: https://github.com/microsoft/winget-pkgs/pull/28175/files

instead of

1. Create a new Manifest
2. Commit new Manifest
3. Delete the old Manifest
4. Commit deletion
5. Publish PR
Example: https://github.com/microsoft/winget-pkgs/pull/28174/files

**Comment by Trenly** [comment]
> Just to be sure, how does this actually work?
> Does it only trigger when you select option 5?
> 
> I've implemented #38 and this which did cause a conflict but i believe it was just spacing difference.
> 
> AFAIK you can't delete a manifest and submit and a new manifest?
> Also i think for it to work the way i want it to work it needs to
> 
> 1. Create a new Manifest
> 2. Delete the old Manifest
> 3. Commit as `New Version: Publisher.PacakgeName version 1.3.3.7`
> 4. Publish PR
>    Example: https://github.com/microsoft/winget-pkgs/pull/28175/files
> 
> instead of
> 
> 1. Create a new Manifest
> 2. Commit new Manifest
> 3. Delete the old Manifest
> 4. Commit deletion
> 5. Publish PR
>    Example: https://github.com/microsoft/winget-pkgs/pull/28174/files

This is an option just for deleting a manifest without adding a new one. This does not implement any logic for automatic deletion, but it does add in the function that such logic would call. 

I agree that when automatic deletion is added it probably should follow the top flow you mentioned

**Comment by OfficialEsco** [comment]
> However, that could make the commit history a bit harder to follow

How? I see no difference in the commit history other than the second flow rewriting the whole thing

**Comment by Trenly** [comment]
> How? I see no difference in the commit history other than the second flow rewriting the whole thing

Exactly; If you're just reading through the commit history of master (Not saying it's a good idea, but just thinking here) then you would see two commits, one for adding the new version and one for removing the old one. It would clarify exactly when the old version was removed. However, I don't think it really matters at all. More just a point of consideration. I agree that this flow
> Create a new Manifest
> Delete the old Manifest
> Commit as New Version: Publisher.PacakgeName version 1.3.3.7
> Publish PR
> Example: https://github.com/microsoft/winget-pkgs/pull/28175/files
would be the best;

**Comment by OfficialEsco** [comment]
> Exactly; If you're just reading through the commit history of master (Not saying it's a good idea, but just thinking here) then you would see two commits, one for adding the new version and one for removing the old one.

IMO it does not really matter when the url is static, because when someone checks the PR it will show that the person only changed the Version number and hash

Version specific urls are not supposed to be updated and you are actually only allowed to delete one and add one version at a time so it very simple to track it down (Bot will throw a error if you delete 2 version and add one version)

**Comment by OfficialEsco** [comment]
Yeye anything is allowed as long as it passes the bots pipeline rules, if it passes the bot rules we moderators can approve it, however you should have a reason other than randomly deleting/replacing old versions.

Your though process might be the same as the wingetbot maintainers, however as a package maintainer and moderator this way is a lot better

**Review by OfficialEsco — APPROVED** [review]
I very very rarely use this and don't see much use in it since we specify in the Title why we delete the manifest (Duplicate url/404)
But it does work so ill approve it so the function is there

**Pull request merged**
