### PR TITLE
Update YamlCreate.ps1

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
null

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Second Issue: After the merge of #18, Custom Switch Prompt is not displayed properly.
```
[Optional] Enter the silent install switch. For example: /S, -verysilent, /qn, --silent
Silent:

[Optional] Enter the silent with progress install switch. For example: /S, -silent, /qb
SilentWithProgress:

[Optional] Enter any custom switches for the installer. For example: /norestart, -norestartCustomSwitch:

[Optional] Enter the installer locale. For example: en-US, en-CA
https://docs.microsoft.com/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a
InstallerLocale:
```

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco @Trenly

**Comment by OfficialEsco** [comment]
Issue 1: Are you sure you are on the right branch? I have this issue when i'm on the Stable Branch which have YamlCreate 1.1.6
Issue 2: I cannot replicate this is PS5 or PS7

Since you closed this and removed all the comments i believe you realized something dumb? 😁

**Comment by OfficialEsco** [comment]
By the way @vedantmgoyal2009 i would recommend that you create a new branch and copy the YamlCreate.ps1 over when there are bigger changes as the branch can bug out after a few merges/rebase on master.
It will be a lot better to work with the YamlCreate once its merged into the stable branch.

**Comment by vedantmgoyal2009** [comment]
> Since you closed this and removed all the comments i believe you realized something dumb? 😁

Yes, I was on the stable branch. That's why I removed everything. Thanks for your reply.

**Pull request closed without merging**
