### PR TITLE
Fix: Prompt for PFN if file does not exist

### LINKED ISSUE #45: Improvement in automatic detection of `PackageFamilyName`
# Description of the new feature/enhancement

When a user selects manual entering of Installer Hash:
image
then the option for finding `PackageFamilyName` should download the URL instead of throwing an error:
image

# Proposed technical implementation details (optional)
if ($null -eq $script:dest)
&nbsp; download the installer
else
&nbsp; continue with installation of package and find `PackageFamilyName`

### PR DESCRIPTION
**Pull request by Trenly**
@vedantmgoyal2009
* Resolves #45

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Well, I was thinking that it should give a message something like this: "You have not downloaded the installer before. Would you like to download the installer and find PackageFamilyName now?"

**Comment by Trenly** [comment]
> Well, I was thinking that it should give a message something like this: "You have not downloaded the installer before. Would you like to download the installer now and find PackageFamilyName?"

It’s possible, but that sort of defeats the whole point of entering the SHA manually; If you are going to download the file to find the PFN, then why wouldn’t you want it to download and find the SHA automatically?

If we add the prompt for if they want to download it for the PFN, then we also have to prompt for if they want to remove it, which has to be tied back to the SHA256 menu in case they already answered the question. 

I guess I’m just not understanding the use case where someone wouldn’t want to download it the first time they are asked to, but then would want to download it the second time.

**Review by vedantmgoyal2009 — APPROVED** [review]
:shipit: You are right. It defeats the whole point of entering the SHA manually.

**Comment by vedantmgoyal2009** [comment]
> If we add the prompt for if they want to download it for the PFN, then we also have to prompt for if they want to remove it, which has to be tied back to the SHA256 menu in case they already answered the question.

I did not think so deeply. It will ruin the user experience if the user has to answer one question two times.

**Review by OfficialEsco — APPROVED** [review]
Approving since @vedantmgoyal2009 approved since hes using this feature more than me

**Pull request merged**
