### PR TITLE
Detect PackageFamilyName for MSIX/APPX

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
Here, I have added the functionality to detect PackageFamilyName for MSIX/APPX Packages. 

> Also about FamilyName and SignatureSha, i've searched around for this before, and from what i found is that it has very little information and support, FamilyName can be found by installing the software and doing get-appxpackage, SignatureSha i have no idea how to read, but for some reason they built it into winget hash

Source: https://github.com/Trenly/winget-pkgs/pull/4#issuecomment-894355849

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco I have already tested on my local machine in every scenario. If it can be useful, please consider approving it.

**Comment by OfficialEsco** [comment]
You've marked it as a draft, you need to put it into Ready for Review

**Review by OfficialEsco — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
Thanks.

**Comment by OfficialEsco** [comment]
Missing a new line here
```
[Recommended] Enter the installer PackageFamilyName
[F] Find Automatically [Note: This will install the pacakge to find Family Name and then removes it.]
[M] Manually Enter PackageFamilyName
Enter Choice (default is 'F'): mPackageFamilyName: R12f.R12f.Rnp_4h335eyz8q7x4
```

**Comment by vedantmgoyal2009** [comment]
Any idea why MSIX/APPX installer validations are failing?

**Comment by OfficialEsco** [comment]
Well it does say why the validation failed, my MSIX showed no issues https://github.com/microsoft/winget-pkgs/pull/24297/files

**Pull request merged**
